import { Link, Stack } from "expo-router";
import { StyleSheet, View, Text } from "react-native";

import { COLORS } from "@/constants/Colors";
//File generated by expo
export default function NotFoundScreen() {
  return (
    <>
      <Stack.Screen options={{ title: 'Oops!' }} />
      <View style={styles.container}>
        <Text style={styles.title} >This screen doesn't exist.</Text>
        <Link href="/" style={styles.link}>
          <Text style={styles.linkText}>Go to home screen!</Text>
        </Link>
      </View>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontWeight: 700,
    fontSize: 20,
    color: COLORS.textNormal,
  },
  linkText: {
    lineHeight: 30,
    fontSize: 16,
    color: COLORS.textLink,
  },
  link: {
    marginTop: 15,
    paddingVertical: 15,
  },
});
