import { StyleSheet, View, Modal } from 'react-native';
import { useState } from 'react';

import { useScale } from '@/hooks/useScale';
import { VideoFlatList } from "../../components/VideoFlatList/VideoFlatList"
import { useDemoData } from '@/hooks/useDemoData';
import { CatalogModal } from '@/components/CatalogModal/CatalogModal';

import type { Nullable } from '@/constants/types';
import type { VideoListItemData } from '@/components/VideoListItem/VideoListItem';
import { COLORS } from '@/constants/Colors';
//File generated by expo, modified

function useHomeScreenViewModel() {
  const { data: videoData } = useDemoData();
  const [focusedItem, setFocusedItem] = useState<Nullable<string>>(null);
  const [modalItem, setModalItem] = useState<Nullable<VideoListItemData>>(null);

  const isModalOpen = modalItem != null;

  const handleItemFocus = (itemId: string) => {
    if (focusedItem == itemId) { return; }
    setFocusedItem(itemId);
  }

  const handleItemPress = (item: VideoListItemData) => {
    setModalItem(item);
  }

  const handleModalClose = () => {
    setModalItem(null);
  }

  return {
    videoData,
    focusedItem,
    isModalOpen,
    modalItem,
    handleItemFocus,
    handleModalClose,
    handleItemPress
  };
}

export default function HomeScreen() {
  const {
    focusedItem,
    isModalOpen,
    modalItem,
    videoData,
    handleItemFocus,
    handleModalClose,
    handleItemPress
  } = useHomeScreenViewModel();

  const styles = useHomeScreenStyles();

  return (
    <View style={styles.container}
    >
      <CatalogModal
        modalItem={modalItem}
        onClose={handleModalClose}
        isOpen={isModalOpen}
      />
      <VideoFlatList
        handleItemFocus={handleItemFocus}
        handleItemPress={handleItemPress}
        focusedItem={focusedItem}
        listItems={videoData}
      />
    </View>
  );
}

const useHomeScreenStyles = function () {
  const scale = useScale();
  return StyleSheet.create({
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8 * scale,
    },
    stepContainer: {
      gap: 8 * scale,
      marginBottom: 8 * scale,
    },
    container: {
      flex: 1,
      backgroundColor: COLORS.containerBackground,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
  });
};
